[config]
transactions = 1000
account = "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA"
commitment = "processed"

[[endpoint]]
name = "Endpoint 1"
url = "http://lon.corvus-labs.io:10101"
kind = "arpc"

[[endpoint]]
name = "Endpoint 2"
url = "http://lon.corvus-labs.io:10101"
kind = "yellowstone"
